#!/bin/sh
#
# umount-nexus:
# unmount a Nexus device.
#
# Syntax:
#
#     umount-nexus [path]
#
# Example:
#
#     umount-nexus
#
# Example using a specific device:
#
#     umount-nexus /media/nexus6
#
# The path defaults to the most recent directory that matches:
#
#     /media/nexus*
#
# This script tries these steps to unmount:
#
#    * use `umount` to unmount the directory
#    * test if the directory still exists
#    * if so, then try `lsof`, then try `fuser`
#
# Command: umount-nexus
# Version: 1.3.0
# Created: 2014-05-26
# Updated: 2016-02-09
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
##
set -euf
out () { printf %s\\n "$*" ; }

dir=${1:=$(ls -1t /media/nexus* | head -1)}

test -e $dir && sudo umount $dir
if [ -e $dir ]; then
  out "Path still exists: $dir"
  out "lsof -w $dir"
  lsof -w $dir
  out
  out "fuser $dir"
  fuser $dir
fi
